AWSTemplateFormatVersion: 2010-09-09
# Mongo DB EOL info: https://www.mongodb.com/legal/support-policy/lifecycles
# MongoDB 5.0: October 2024
# Rocky Linux EOL info: https://endoflife.date/rocky-linux
# 8: 01 May 2021 (Security Support: 31 May 2024)
# Ref: https://www.hopes.host/blog/mongodb-install

Parameters:
  AllowIP:
    Type: String
  VPC:
    Type: AWS::EC2::VPC::Id
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
  InstanceType:
    Type: String
    Default: t2.large
  VPCCIDR:
    Type: String

Mappings:
  RegionMap:
    us-east-1:
      RockyLinux8: ami-011ef2017d41cb239
    ap-northeast-1:
      RockyLinux8: ami-0c38a5fa7b9dbd96c

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "MongoDB Security Group"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: -1
          FromPort: 27017
          ToPort: 27017
          CidrIp: !Ref VPCCIDR
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  MongoDBRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AdministratorAccess
      Path: /

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref MongoDBRole

  MongoDB:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - RockyLinux8
      InstanceType: !Ref InstanceType
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          GroupSet:
            - Ref: SecurityGroup
          SubnetId:
            Ref: PublicSubnet1
      Tags:
      - Key: Name
        Value: MongoDB
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash -x
            download(){  
            until curl -f $@ ; 
            do
            sleep 1
            done
            }
            echo "[mongodb-org-5.0]" >> /etc/yum.repos.d/mongodb-org-5.0.repo 
            echo "name=MongoDB Repository" >> /etc/yum.repos.d/mongodb-org-5.0.repo 
            echo "baseurl=https://repo.mongodb.org/yum/redhat/8/mongodb-org/5.0/x86_64/" >> /etc/yum.repos.d/mongodb-org-5.0.repo 
            echo "gpgcheck=1" >> /etc/yum.repos.d/mongodb-org-5.0.repo 
            echo "enabled=1" >> /etc/yum.repos.d/mongodb-org-5.0.repo 
            echo "gpgkey=https://pgp.mongodb.com/server-5.0.asc" >> /etc/yum.repos.d/mongodb-org-5.0.repo 
            yum install -y mongodb-org
            systemctl start mongod
            systemctl enable mongod

Outputs:
  MongoDBPublicIp:
    Description: MongoDB's public Ip address
    Value: !GetAtt MongoDB.PublicIp
