AWSTemplateFormatVersion: "2010-09-09"

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-tnogi-dev-ap-northeast-1.s3.amazonaws.com/vpc-template.yml
