AWSTemplateFormatVersion: "2010-09-09"

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:  !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}challenges/example_challenge/templates/example.main.template.yaml'
