name: CloudFormation Guard validate

on:
#  pull_request:
  push:

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  check-cfn-templates:
    name: Check AWS CloudFormation templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: 'arn:aws:iam::209746572579:role/tnogi-admin'
          aws-region: ap-northeast-1

      - name: install and run CloudFormation Guard
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh | sh
          export PATH="$HOME/.guard/bin:$PATH"
          echo "Installed cfn-guard"
          cfn-guard --version
          echo "cfn-guard version showed"

          cfn-guard rulegen --template ./infra/ec2-template.yml --output s3.guard
          cat s3.guard
          
