# https://techblog.forgevision.com/entry/cloudformation-guard
name: CloudFormation Guard validate

on:
  push:
    branches: 
      - main
  pull_request_target:
    types:
      - opened
      - synchronize
    branches: 
      - main
  workflow_dispatch:

jobs:
  check-cfn-templates:
    name: Check AWS CloudFormation templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install and run CloudFormation Guard
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh | sh
          export PATH="$HOME/.guard/bin:$PATH"
          echo "Installed cfn-guard"
          cfn-guard --version
          echo "cfn-guard version showed"

          cfn-guard validate --data ./infra/k8s-bastion-template.yml --rules ./cfn-guard-rules/ruleset --show-summary all
          cfn-guard validate --data ./infra/main-template.yml --rules ./cfn-guard-rules/ruleset --show-summary all
          cfn-guard validate --data ./infra/vpc-template.yml --rules ./cfn-guard-rules/ruleset --show-summary all
          cfn-guard validate --data ./infra/ec2-template.yml --rules ./cfn-guard-rules/ruleset --show-summary all          
