name: CloudFormation Guard validate

on:
  push:

jobs:
  guard:
    runs-on: ubuntu-latest
    name: CloudFormation Guard validate
    steps:
      - name: CloudFormation Guard validate
        uses: aws-cloudformation/cloudformation-guard@action-v0.0.5
        with:
          rules: ./cfn-guard-rules/ruleset
          data: './infra'
