name: Deploy CFn Stack

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/**'

permissions:
  id-token: write
  contents: read
  packages: read

env:
  WORKING_DIRECTORY: infra
  REGION_NAME: ap-northeast-1
  YAML_NAME: main-template.yml
  STACK_NAME: infra-cfn

jobs:
  deploy-cfn:
    name: Deploy CFn Stack to AWS
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: 'arn:aws:iam::209746572579:role/tnogi-admin'
        aws-region: ap-northeast-1

    - name: Check how many templates changed
      id: templates
      run: |
        changed_templates=$(git diff HEAD^ --name-only | grep -c ${{ env.WORKING_DIRECTORY }}/)
        echo changed_templates=$changed_templates >> "$GITHUB_OUTPUT"

    - name: Upload to S3
      if: ${{ steps.templates.outputs.changed_templates > 0 }};
      run: |
        templates=$(git diff HEAD^ --name-status | grep ${{ env.WORKING_DIRECTORY }}/ | grep "^M\|^A" | cut -f2)
        for template in $templates; do
          aws s3 cp $template s3://cf-templates-tnogi-dev-ap-northeast-1
        done

    - name: Deploy CFn Stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      if: ${{ steps.templates.outputs.changed_templates > 0 }};
      with:
        name: infra-cfn
        template: https://cf-templates-tnogi-dev-ap-northeast-1.s3.amazonaws.com/main-template.yml
        no-fail-on-empty-changeset: 1
        capabilities: CAPABILITY_NAMED_IAM
